build: fix compile error when -Werror=return-type is used
ReadPolyhedron.cpp: In member function ‘RationalNTL ReadPolyhedronDataRecursive::getNormalFactor() const’:
ReadPolyhedron.cpp:1228:1: error: control reaches end of non-void function [-Werror=return-type]
 1228 | }//ReadPolyhedronDataRecursive
      | ^